### ISSUE TITLE
ValueError: need at least one array to concatenate

### ISSUE THREAD

**Issue by Myblackcat0216** [ymhzyj/UMMAFormer#1]
Hello, is the video frame to be extracted in advance? Running the code to extract visual features directly will report an error：ValueError: need at least one array to concatenate

**Comment by ymhzyj** [comment]
Yes, you need extract frames and optical flow  frames from videos. You can refer to the [mmaction]( https://github.com/open-mmlab/mmaction2/tree/main/tools/data/activitynet).
