### ISSUE TITLE
where is the implementation of the class "AudioNTT2020Feature"?

### ISSUE THREAD

**Issue by BlackPuuuudding** [ymhzyj/UMMAFormer#11]
in byola_extract_lavdf.py,"from byol_a.models import AudioNTT2020Feature".
but i cant find class AudioNTT2020Feature in byol_a.models.
could you please share the code of AudioNTT2020Feature? that would be a lot to me.
thanks!

**Comment by ymhzyj** [comment]
You can use AudioNTT2020Task6 as it is
