### ISSUE TITLE
How to extract flow and frames 

### ISSUE THREAD

**Issue by Alane-Henry** [ymhzyj/UMMAFormer#13]
Great job!
However, I met a problem when replicating this.
" Furthermore, you need to extract frames and optical flow from the videos. You can use mmaction for this purpose."
Can you explain in detai how you used mmaction to extract frames and optical flow from the videos?

**Comment by ymhzyj** [comment]
You can refer this [extact_frames.sh](https://github.com/open-mmlab/mmaction2/blob/main/tools/data/activitynet/extract_frames.sh)

**Comment by Alane-Henry** [comment]
Thanks, but could you provide the exact script you guys used so that I can replicate your result in the paper truthfully?

**Comment by ymhzyj** [comment]
I'm sorry, but I'm having difficulty finding the script. However, we didn't perform any special processing on the script; we simply extracted the images and optical flow based on the original dimensions of the video.

**Comment by Alane-Henry** [comment]
Fine, but what kind of method have you used to extract the optical flow? tvl1? And what about the bouding of flow distance,which 20 if you uesd the default setting of mmaction.Thanks

**Comment by ymhzyj** [comment]
Yes, the optical flow uses TVL1, and all settings are the default settings of mmaction without any modifications.

**Comment by ymhzyj** [comment]
[000485.zip](https://github.com/user-attachments/files/17144829/000485.zip)
Here is an example we extracted.

**Comment by Alane-Henry** [comment]
OK，Thank you!
