### ISSUE TITLE
compile problem

### ISSUE THREAD

**Issue by SoberDanz** [ymhzyj/UMMAFormer#14]
When I replaced the PyTorch version with a newer one, even after re-running python setup.py install to compile, I still encountered the following runtime error: nms_1d_cpu.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK3c1010TensorImpl36is_contiguous_nondefault_policy_implENS_12MemoryFormatE.

**Comment by ymhzyj** [comment]
I'm sorry, but this question is difficult for me to answer. It might be better to discuss it further on the official PyTorch forum.
