### ISSUE TITLE
Help with inference

### ISSUE THREAD

**Issue by AntonThai2022** [ymhzyj/UMMAFormer#16]
Hello! I figured out how to train and do evaluetion. But how to make an inference model? Is it possible to somehow check on a random video whether it is a deepfake or not? Please tell me!

**Comment by zzzby-star** [comment]
你好，请问你能成功训练论文中的数据吗？

**Comment by ymhzyj** [comment]
I did not write inference code; instead, I simply performed inference by creating a separate JSON file, referencing the annotation format, and assigning arbitrary fake labels to obtain the inference results for use. If you want to perform inference, you should refer to the evaluation process used in testing. You only need to remove the sections related to labels in data reading and evaluation. If you have written the code, you're welcome to contribute it back to the original source as well.
