### ISSUE TITLE
AudioNTT2020Feature

### ISSUE THREAD

**Issue by Myblackcat0216** [ymhzyj/UMMAFormer#2]
Hello, what is the AudioNTT2020Feature from byol_a.models import AudioNTT2020Feature in byola_extract_lavdf.py
Traceback (most recent call last):
  File "/home/UMMAFormer-main/bylo-a/byola_extract_lavdf.py", line 3, in <module>
    from byol_a.models import AudioNTT2020Feature
ImportError: cannot import name 'AudioNTT2020Feature' from 'byol_a.models' (/home/UMMAFormer-main/bylo-a/byol_a/models.py)
Another question is what parameters need to be changed when extracting audio features using byol-a？
Thank you for your excellent work and look forward to your reply

**Comment by ymhzyj** [comment]
Thank you for your attention. If you want to use BYOL-A to extract features, you need to use the code available at https://github.com/nttcslab/byol-a. What I provided is just a basic example of calling the relevant code.

**Comment by daisukelab** [comment]
@ymhzyj Dear author, thank you for using BYOL-A and excuse me for cutting in.
Is `AudioNTT2020Feature`  the same as `AudioNTT2020Task6`? That could be the answer to the question.
https://github.com/nttcslab/byol-a/blob/master/byol_a/models.py#L48

@Myblackcat0216 I think you can use `AudioNTT2020Task6` if you want to extract audio features for each time frame.
If you want a single feature vector for an audio clip, please try `AudioNTT2020` instead.

**Comment by Myblackcat0216** [comment]
Thank you very much for your help. It solved my problem
