### ISSUE TITLE
Pretrained model links not working

### ISSUE THREAD

**Issue by Hina-Anwar** [ymhzyj/UMMAFormer#3]
Hi , can you please share link for pretrained models for Audio +video forgery detection, given CKPT links not working

**Comment by ymhzyj** [comment]
Thank you for your attention. We have uploaded our model to [OneDrive](https://1drv.ms/u/s!AgVmq0AY0Su8grtFydwbVa-fdxMdmQ?e=H71mMB).

**Comment by Hina-Anwar** [comment]
thank you
