### ISSUE TITLE
python tools/test_miou.py

### ISSUE THREAD

**Issue by xiaoxutongxu** [ymhzyj/UMMAFormer#4]
我使用python tools/test_miou.py这行代码测试TVIL数据集显示test_cellular iou:nan 和test_cellular iou best:nan

**Comment by ymhzyj** [comment]
I don't have additional information to determine the cause of your issue. We haven't encountered this particular bug in our testing. My understanding is that there may be an issue with the data or labels you're reading. I recommend finding someone with experience in debugging Python code to further investigate and debug the issue in detail.
