### ISSUE TITLE
could not find the code about the PCA-FPN

### ISSUE THREAD

**Issue by garlicyh** [ymhzyj/UMMAFormer#6]
hey, i only find the FPN code in the neck.py, cant find the cross attention function in it.
so where is the code of PCA-FPN? 
looking forward to your reply.  thanks!!
@ymhzyj

**Comment by ymhzyj** [comment]
Most of the content is in the backbone, combined with FPN, forming PCA-FPN. I may further integrate the code later, but the code is currently separate.
