### ISSUE TITLE
Long time when test on lav-df

### ISSUE THREAD

**Issue by garlicyh** [ymhzyj/UMMAFormer#7]
hey, when i test on lav-df, i found it's a time-consuming process, which i stuck here for almost an hour.
![image](https://github.com/ymhzyj/UMMAFormer/assets/103733635/cb1a25a3-7815-4818-8037-a6bb8df85785)
is it normal? @ymhzyj

**Comment by ymhzyj** [comment]
Yes, this is a normal phenomenon. Due to my limited capabilities, I am temporarily unable to further optimize the evaluation code, I apologize.
