### ISSUE TITLE
Visualisation tool scripts

### ISSUE THREAD

**Issue by angelaragonkifute** [ymhzyj/UMMAFormer#8]
Both in the paper and in the repository some visualisation tool is showed where a video is played and there are two bars below showing ground truth and prediction, could you provide those scripts or the references of the repositories where those scripts where taken? They could be really useful for visualisation.

Thanks beforehand.

<img width="613" alt="Screenshot 2024-04-15 at 14 21 07" src="https://github.com/ymhzyj/UMMAFormer/assets/110982543/9b336270-5d20-451c-bedc-baaf0c908a1f">

**Comment by ymhzyj** [comment]
We use this python lib [vistal](https://github.com/x4Cx58x54/vistal)
